name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rust-src
    - name: Build
      run: cargo build --release --verbose --target=i686-win7-windows-msvc
      
    - name: Move artifact
      run: move .\target\i686-pc-windows-msvc\release\gm82live.dll gm82live.dll

    - name: Download gm82gex
      run: curl https://raw.githubusercontent.com/GM82Project/gm82gex/main/gm82gex.py -o gm82gex.py

    - name: Build .gex
      run: python gm82gex.py ${{github.workspace}}/gm82live.gej --noinstall

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gm82live
        path: gm82live.gex
