name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        target: i686-pc-windows-msvc
        toolchain: stable
    - name: Build
      run: cargo build --release --verbose

    - name: Download gm82gex
      run: wget https://raw.githubusercontent.com/GM82Project/gm82gex/main/gm82gex.py

    - name: Build .gex
      run: python gm82gex.py ${{github.workspace}}/gm82live.gej --noinstall

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gm82live
        path: gm82live.gex
